config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      post '/mail/:task_id', to: 'contacts#sending', as: :mail
      get 'alltask', to: 'tasks#index', as: :all_task
      get 'new_task', to: 'tasks#new'
      post 'new_task', to: 'tasks#create'
      get '/edit_task/:task_id', to: 'tasks#edit', as: :edit_task
      get '/task/:task_id', to: 'tasks#show', as: :show_task
      post '/task_total/:task_id', to: 'tasks#update_total', as: :task_total
      patch '/update_task/:task_id', to: 'tasks#update', as: :update_task
      delete '/delete_task/:task_id', to: 'tasks#destroy', as: :delete_task
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
      validates :name,  presence: true
      validates :detail,  presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
     before_action :set_user, only: [:new, :create, :edit, :upadate, :index]
     before_action :logged_in_user, only: [:new, :create, :edit, :update, :index]

    def index
        @alltask = Task.all
        @tasks = Kaminari.paginate_array(@alltask).page(params[:page]).per(10)
    end
    
    def new
        @task = Task.new
    end
    
    def edit
        @task = Task.find(params[:task_id])
    end
    
    def show
        @task = Task.find(params[:task_id])
    end
    
    def create
        @task = Task.new(task_params)
        @task.user_id = @user.id
        if @task.save
            flash[:success] = 'タスク作成致しました。'
            redirect_to user_path
        else
            render :new
        end
    end
    
    def update
        @task = Task.find(params[:task_id])
        if @task.update_attributes(task_update_params)
            flash[:success] = "タスクを更新しました。"
        else
            flash[:danger] = "タスク更新に失敗しました。<br>" + @task.errors.full_messages.join("<br>")
            render :edit
        end
        redirect_to user_path
    end
    
    def update_total
        @task = Task.find(params[:task_id])
        task_new_total = @task.total.to_f + params[:total].to_f
        @task.total = task_new_total.to_f.floor(2)
        if @task.save
            flash[:success] = "タスクを更新しました。"
            redirect_to user_path
        else
            flash[:danger] = "タスク更新に失敗しました。"
            redirect_to user_path
        end
    end
    
    def destroy
        @task = Task.find(params[:task_id])
        @task.destroy
        flash[:success] = "タスクを削除しました。"
        redirect_to user_path
  end


    private

        def task_params
            params.permit(:name, :detail, :start_day, :finish_day)
        end
        
        def task_total_params
            params.permit(:name, :total)
        end
        
        def task_update_params
            params.require(:task).permit(:name, :detail, :start_day, :finish_day, :progress, :status, :total)
        end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>
<% provide(:button_text, '更新') %>
<h1 class="base-font-color">タスク編集</h1>

<div class="row form-font-color">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @task, url: update_task_user_path, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @task %>

      <%= f.label :name, class: "label-task" %>
      <%= f.text_field :name, class: "form-control", required: true %>

      <%= f.label :detail, class: "label-task" %>
      <%= f.text_area :detail, class: "form-control", required: true %>

      <%= f.label :start_day, class: "label-task" %>
      <%= f.date_field :start_day, class: "form-control" %>

      <%= f.label :finish_day, class: "label-task" %>
      <%= f.date_field:finish_day, class: "form-control" %>
      
      <%= f.label :status, class: "label-task" %>
      <%= f.select :status, {'未完了': false, '完了': true}, { include_blank: false }, { class: 'form-control' }%>
      
      <%= f.label :progress, class: "label-task" %>
      <div class="task-progress">
        <span>0%</span><%= f.range_field :progress, in: 1..100, class: "form-control" %><span>100%</span>  
      </div>
      
      <%= f.label :total, class: "label-task" %>
      <div class="task-total">
        <%= f.number_field :total, in: 1.0..200.0, step: 0.1, class: "form-control" %><span>時間</span>
      </div>
      

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-task" %>
      
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, 'All Tasks') %>
<h1 class="base-font-color">タスク一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <% if @tasks %>
    <%= will_paginate %>
    <table class="table table-condensed base-font-color" id="table-users">
      <thead>
        <tr>
          <th>タスク名</th>
          <th class="center">詳細</th>
          <th>学習時間</th>
          <th>進捗時間</th>
        </tr>
      </thead>

      <% @tasks.each do |task| %>
        <tr>
          <td>
            <%= link_to task.name, show_task_user_path(@user, task.id), class: "base-font-color" %>
          </td>
          <td class="center"><%= task.detail %></td>
          <td class="center"><%= task.total %>時間</td>
          <td class="center"><%= task.progress %>%</td>
          <td class="center">
            <%= link_to "編集", edit_task_user_path(@user, task.id), class: "btn btn-success"  %>
            <%= link_to "削除", delete_task_user_path(@user, task.id) , method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate %>
  <% else %>
    現在学習中のものはございません。
  <% end %>
</div>

<style>
  .container {
    color: #fff;
  }
</style>

app/views/tasks/new.html.erb
<% provide(:title, 'New Task') %>
<% provide(:button_text, '新規作成') %>
<h1 class="base-font-color">タスク登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form-font-color">
    <%= form_with(model: @tasks, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @task %>

      <%= f.label "名前", class: "label-task" %>
      <%= f.text_field :name, class: "form-control", required: true %>

      <%= f.label "詳細", class: "label-task" %>
      <%= f.text_area :detail, class: "form-control", required: true %>

      <%= f.label "開始予定日", class: "label-task" %>
      <%= f.date_field :start_day, class: "form-control" %>

      <%= f.label "終了予定日", class: "label-task" %>
      <%= f.date_field:finish_day, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-task" %>
      
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, 'Show Task') %>
<% provide(:button_text, '学習時間合算') %>
<div class="task-show">
  <h1>タスク詳細</h1>
  <div class="row">
    <div>
      <div class="task-content">
        <div class="task-icon"><img src="https://joeschmoe.io/api/v1/random" /></div>
        <div class="task-content-title"><%= @task.name %></div>
        <div class="task-content-detail"><%= @task.detail %></div>
        <div class="task-content-detail">合計<%= @task.total.to_f %>時間</div>
        <div class='task-select'>
          <%= form_with(model: @task, url: update_task_user_path, local: true, id: "task-form") do |f| %>
            <%= f.label :status, class: "label-task task-content-detail" %>
            <%= f.select :status, {'未完了': false, '完了': true}, { include_blank: false }, { class: "form-control task-select" }%>
          <% end %>
        </div>
        <div class='task-total'>
          <%= form_with( url: task_total_user_path, local: true, id: "task-total") do |f| %>
            <%= f.label "学習時間", class: "label-task task-content-detail" %>
            <%= f.number_field :total, in: 1.0..200.0, step: 0.1, class: "form-control" %><span>時間</span>
            <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-task" %><br>
            <span class="text-info">※学習した時間を入力し、学習時間合算ボタンをクリックしてください。</span>
          <% end %>
        </div>
        <div class="task-graph">
          <%# グラフ %>
          <%= bar_chart [['進捗', @task.progress]], min: 0, max: 100, height: "60px" %>
        </div>
        <div id="timer">
          <div class="task-stopwatch">
            <div class="timer_name">学習時間</div>
            <p id="timer_text">
              <span id="hour">00</span> :
              <span id="min">00</span> :
              <span id="sec">00</span>
            </p>
          </div>
          <div class="btn-group btn-group-lg" role="group" >
            <button type="button" class="btn btn-info" id="reset" disabled>Reset</button>
            <button type="button" class="btn btn-info" id="start">Start</button>
            <button type="button" class="btn btn-info" id="stop" disabled>Stop</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
//localStorageには[started_at, working_on, min_time, hour_time]の４つの変数が保持されている。

(function(){
  
$('select').change( function() {
    var ret = confirm("更新してもよろしいですか？");
    if(!ret){
      return false;
    }
    $('#task-form').submit();
})

var call_function_each = 100

var mid = 0;
var now;


var hour_time = 0;
var min_time = 0;
var sec_time = 0;

var count;

var hour = $("#hour");
var min = $("#min");
var sec = $("#sec");

var start = $("#start");
var stop = $("#stop");
var reset = $("#reset");

//localStorageにどちらの値もない場合は処理する必要ないので始めに条件分岐
if(localStorage.getItem('started_at')){
  //ページ読み込みされたときに自動で行われる処理
  window.onload = function(){
    min_time  = Number(localStorage.getItem('min_time'));
    hour_time = Number(localStorage.getItem('hour_time'));
    count = setInterval(counter, call_function_each);
    toggle();
  }
}

if(localStorage.getItem('working_on') && !localStorage.getItem('started_at')){
  window.onload = function(){
    //以下のコードで経過時刻を取得
    sec_time  = Number(localStorage.getItem('working_on'));
    min_time  = Number(localStorage.getItem('min_time'));
    hour_time = Number(localStorage.getItem('hour_time'));
    //以下のコードで経過時刻を表示

    if(sec_time < 9.5){
      sec.html("0"+sec_time.toFixed(0));
    }else if(sec_time < 10.5){
      sec.html("10");
    }else{
      sec.html(sec_time.toFixed(0));
    }

    if(min_time < 10){
      min.html("0"+min_time);
    }else{
      min.html(min_time);
    }

    if(hour_time < 10){
      hour.html("0"+hour_time);
    }else{
      hour.html(hour_time);
    }

    toggle();
  }  
}

//startボタンが押された時の処理.
start.click(function(){
  //localStorageに開始時刻が記録されているのに呼び出すと、データが初期化されるため条件分岐している。
  now = new Date(); //現在時刻
  localStorage.setItem('started_at', now);

  $("#test").text(typeof localStorage.getItem('started_at'));
  $("#test2").text(typeof localStorage.getItem('working_on'));
  count = setInterval(counter, call_function_each);
  toggle();
});

//stopボタンが押された時の処理
stop.click(function(){
  mid += (new Date() - now)/1000;
  localStorage.setItem('working_on', mid);
  localStorage.removeItem('started_at');
  $("#test").text(typeof localStorage.getItem('started_at'));
  $("#test2").text(typeof localStorage.getItem('working_on'));
  clearInterval(count);
  toggle();
});

//resetボタンが押された時の処理
reset.click(function(){
  mid = 0;
  localStorage.clear();
  $("#test").text(typeof localStorage.getItem('started_at'));
  $("#test2").text(typeof localStorage.getItem('working_on'));
  hour_time = 0;
  min_time = 0;
  hour.html("00");
  min.html("00");
  sec.html("00");
  reset.prop("disabled", "gray");
});
//時間の計算
function counter(){
  if(localStorage.getItem('started_at')){
    var now2 = localStorage.getItem('started_at');
    now = Date.parse(now2);
  }

  if(localStorage.getItem('working_on')){
    var mid2 = localStorage.getItem('working_on');
    mid = Number(mid2);
  }

  sec_time = mid + ((new Date() - now)/1000);

  //60秒経過した時の処理
  if(sec_time > 59.4){
      mid = 0;
      localStorage.removeItem('working_on');
      min_time ++;
      localStorage.setItem('min_time',min_time);
      now = new Date();
      localStorage.setItem('started_at', now);
      sec_time = 0;
      sec.html();
  }

  if(min_time > 59.4){
      hour_time ++;
      localStorage.setItem('hour_time', hour_time);
      min_time = 0;
      min.html();
  }

  //秒数が10秒より小さかったら01, 02のようにする
  //Note : .5以上の場合は次の数字に切り替わる
  if(sec_time < 9.5){
      sec.html("0"+sec_time.toFixed(0));
  }else if(sec_time < 10.5){
      sec.html("10");
  }
  else{
      sec.html(sec_time.toFixed(0));
  }
  //分数の表示のコード
  if(min_time < 10){
      min.html("0"+min_time);
  }else{
      min.html(min_time);
  }
  //時数の表示のコード
  if(hour_time < 10){
      hour.html("0"+hour_time);
  }else{
      hour.html(hour_time);
  }

  $("#test").text(typeof localStorage.getItem('started_at'));
  $("#test2").text(typeof localStorage.getItem('working_on'));
}

//ボタンの切り替え

function toggle(){
  if(!localStorage.getItem('started_at')){
      start.prop("disabled", false);
      stop.prop("disabled", true);
      reset.prop("disabled", false);
  }else if(!start.prop("disabled")){
      start.prop("disabled", true);
      stop.prop("disabled", false);
      reset.prop("disabled", true);
  }else{
      start.prop("disabled", false);
      stop.prop("disabled", true);
      reset.prop("disabled", false);
  }
}
})();

$('.btn-task').click( function() {
    var ret = confirm("学習時間を合算してもよろしいですか？");
    if(!ret){
      return false;
    }
    $('#task-total').submit();
})

</script>