config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      post '/mail/:task_id', to: 'contacts#sending', as: :mail
      get 'alltask', to: 'tasks#index', as: :all_task
      get 'new_task', to: 'tasks#new'
      post 'new_task', to: 'tasks#create'
      get '/edit_task/:task_id', to: 'tasks#edit', as: :edit_task
      get '/task/:task_id', to: 'tasks#show', as: :show_task
      post '/task_total/:task_id', to: 'tasks#update_total', as: :task_total
      patch '/update_task/:task_id', to: 'tasks#update', as: :update_task
      delete '/delete_task/:task_id', to: 'tasks#destroy', as: :delete_task
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'httpclient'
  require 'net/http'
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]

  def show
    require 'news-api'
    news = News.new(ENV['NEWS_API_KEY'])
    @allnews = news.get_top_headlines(country: 'jp')
    @news = Kaminari.paginate_array(@allnews).page(params[:page]).per(3)
    
    @tasks = Task.where(user_id: @user.id).where(status: false)
    @sum = 10
    
    @post = Post.find(@user.post_id)
    
    # hash形式でパラメタ文字列を指定し、URL形式にエンコード
    params = URI.encode_www_form({q: @post.name, units: 'metric', appid: ENV['WEATHER_API_KEY']})
    # URIを解析し、hostやportをバラバラに取得できるようにする
    uri = URI.parse("http://api.openweathermap.org/data/2.5/forecast?#{params}")
    # リクエストパラメタを、インスタンス変数に格納
    @query = uri.query

    # 新しくHTTPセッションを開始し、結果をresponseへ格納
    response = Net::HTTP.start(uri.host, uri.port) do |http|
      # 接続時に待つ最大秒数を設定
      http.open_timeout = 5
      # 読み込み一回でブロックして良い最大秒数を設定
      http.read_timeout = 10
      # ここでWebAPIを叩いている
      # Net::HTTPResponseのインスタンスが返ってくる
      http.get(uri.request_uri)
    end
    # 例外処理の開始
    begin
      # responseの値に応じて処理を分ける
      case response
      # 成功した場合
      when Net::HTTPSuccess
        # responseのbody要素をJSON形式で解釈し、hashに変換
        @result = JSON.parse(response.body)
        # 表示用の変数に結果を格納
        
        # 天気
        @weather = @result["list"][0]["weather"][0]["description"]
        if @weather = "clear sky"
          @weather = "晴れ"
          @img_url = 'clear_sky.png'
        elsif @weather = "scattered cloud"
          @weather = "曇りのち晴れ"
          @img_url = 'scattered_cloud.png'
        elsif  @weather = "thunderstorm rain"
          @weather = "雨のち雷"
          @img_url = 'thunderstorm_rain.png'
        elsif  @weather = "thunderstorm"
          @weather = "雷"
          @img_url = 'thunderstorm.png'
        elsif  @weather = "rain"
          @weather = "雨"
          @img_url = 'rain.png'
        elsif  @weather = "snow"
          @weather = "雪"
          @img_url = 'snow.png'
        elsif  @weather = "light rain"
          @weather = "小雨"
          @img_url = 'light_rain.png'
        elsif  @weather = "drizzle"
          @weather = "霧"
          @img_url = 'drizzle.png'
        elsif  @weather = "cloud"
          @weather = "曇り"
          @img_url = 'cloud.png'
        end
        
        # 今の気温
        @now_temp_max = @result["list"][0]["main"]["temp_max"]
        
        # 3時間後の気温
        @three_temp_max = @result["list"][3]["main"]["temp_max"]
        
        # 6時間後の気温
        @six_temp_max = @result["list"][6]["main"]["temp_max"]
        
        # 9時間後の気温
        @nine_temp_max = @result["list"][6]["main"]["temp_max"]
        
        # 最低気温
        @temp_min = @result["list"][0]["main"]["temp_min"]
        
        # 風速
        @speed = @result["list"][0]["wind"]["speed"]
        
      # 別のURLに飛ばされた場合
      when Net::HTTPRedirection
        @message = "Redirection: code=#{response.code} message=#{response.message}"
      # その他エラー
      else
        @message = "HTTP ERROR: code=#{response.code} message=#{response.message}"
      end
    # エラー時処理
    rescue IOError => e
      @message = "e.message"
    rescue TimeoutError => e
      @message = "e.message"
    rescue JSON::ParserError => e
      @message = "e.message"
    rescue => e
      @message = "e.message"
    end
    
    @today = Date.today
    day = Date.today.wday
    days = ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"]
    @week = days[day]
  end
    

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
    flash[:success] = "#{@user.name}の基本情報を更新しました。"
  else
    flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
  end
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :post_id)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :post_id, class: "label-#{yield(:class_text)}" %>
  <%= f.select :post_id, options_for_select(Post.post_areas, selected: @user.post_id), { include_blank: false }, { class: 'form-control' }%>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1 class="base-font-color">ユーザー情報の更新</h1>

<div class="row form-font-color">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<style>
  .row {
    color: #fff;
  }
</style>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1 class="base-font-color">ユーザー登録</h1>

<div class="row form-font-color">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<style>
  .container {
    color: #fff;
  }
</style>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <th>名前</th>
      <th>日付</th>
      <th>曜日</th>
    </tr>

    <tr>
      <td><%= @user.name %></td>
      <td><%= Date.today %></td>
      <td><%= @week %></td>
    </tr>
  </table>
</div>
<div>
  <div class="task-box">
    <h2>タスク一覧</h2>
    <ul>
      <% @tasks.each do |task| %>
        <li>
            <% if task.finish_day < @today %>
              <span class="task-name text-danger"><%= link_to task.name, show_task_user_path(@user, task.id), class: "text-danger" %>
            <% else %>
              <span class="task-name"><%= link_to task.name, show_task_user_path(@user, task.id) %></span>
            <% end %>
            <%= link_to "編集", edit_task_user_path(@user, task.id), class: "btn btn-success"  %>
            <%= link_to "削除", delete_task_user_path(@user, task.id) , method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
        </li>
        <div class="task-message">
          <% if task.finish_day && task.finish_day < @today  %>
            <span class="text-danger"><%= task.finish_day.strftime('%Y/%m/%d') %>に終了予定でしたが、期限を過ぎています。</span>
          <% elsif task.finish_day %>
            <span class="text-info"><%= task.finish_day.strftime('%Y/%m/%d') %>までに終了予定です。</span>
          <% else %>
            未定
          <% end %>
        </div>
        <div class="task-graph">
          <%# グラフ %>
          <%= bar_chart [['進捗', task.progress]], min: 0, max: 100, height: "60px" %>
        </div>
        <div class="task-line">
          <%= link_to "タスクをmailで送信", mail_user_path(@user,task.id), method: :post,
            data: { confirm: "mailを送信してよろしいですか？" }, class: "btn btn-info"  %>
        </div>
      <% end %>
    </ul>
    <div class="task-btn">
      <%= link_to "タスク新規作成", new_task_user_path(@user), class: "btn btn-primary" %>
    </div>
    <div class="task-btn">
      <%= link_to "タスク一覧（完了含む）", all_task_user_path(@user), class: "btn btn-primary" %>
    </div>
  </div>
</div>
<div class="slick">
  <div>
    <div class="weather-box">
      <div class="weather">
        <h2 class="weather-box-title">本日の天気（<%= @post.name %>）</h2>
        <div><%= image_tag @img_url %></div>
        <div class="weather-content"><%= @weather %></div>
        <%= line_chart [['今の気温', @now_temp_max.round(1)],['3時間後の気温', @three_temp_max.round(1)],['6時間後の気温', @six_temp_max.round(1)],['9時間後の気温', @nine_temp_max.round(1)]], min: 0, max: 30, height: "200px" %>
      </div>
      <div class="scenery">
        <img src="https://source.unsplash.com/random">
      </div>
    </div>    
  </div>

  <div>
    <div class="map" >
      <h2><%= @post.name %>の周辺情報</h2>
      <!-- 地名入力用のinputを追加 -->
      <input id="address" type="textbox" class="form-control" value="<%= @post.name %>" >
      <span>※地名を入力してください。</span><br>
      <!-- buttonをクリックしたらcodeAddressを実行　-->
      <input type="button" value="検索" class="btn btn-info" onclick="codeAddress()">
      <div id='map'></div> 
    </div>
  </div>
  <div class="news">
  <% @news.each do |news| %>
    <div class="news-box">
      <%= link_to news.url do %>
        <% if news.urlToImage.present? %>
          <%= image_tag(news.urlToImage, class: "item-img") %>
        <% else %>
          <%= image_tag("dammy-cover.png", class: "item-img") %> 
        <% end %>
        <div class="article-body">
          <p class="article-title-name">
            <%= news.title.truncate(30) %>
          </p>
        </div>
      <% end %>
      <div class="tags">
        <div class="article-body">
          <div class="article-user">
            <%= news.author %>
          </div>
        </div>
        <div class="created-time">
          <%= time_ago_in_words(news.publishedAt) %>前
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @news %>
  </div>
</div>


<style>

#map{
  height: 400px;
}

</style>

<script>
let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: <%= @post.latitude %>, lng: <%= @post.longitude %> },
  zoom: 10
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY'] %>&callback=initMap" async defer></script>